feature/tj/modelado-bd
ErikMurmi/reservas-udla pull request #1
Opened 2023-09-10 23:34 UTC by titorjs

Cambios del modelo de la base de datos:
- IDBanner a Varchar(9)
- CanchaID en solicitud
- ID autoincremental

Modelado de las clases

2023-09-11 19:57 UTC, ErikMurmi requested changes
Deje unos comentarios, revisale. Lo demás se ve bien!!

2023-09-11 19:57 UTC, ErikMurmi commented on docs/reservas_canchas_udla_db.sql
> +	CONSTRAINT canchaFK2 FOREIGN KEY (CanchaID) REFERENCES Cancha(ID),
En caso de repertirse el nombre un FK busquemos una alternativa que mantenga la legibilidad, si ponemos el 2 al final podemos terminar con muchos iguales y no sabremos diferenciar
```suggestion
	CONSTRAINT solictud_canchaFK FOREIGN KEY (CanchaID) REFERENCES Cancha(ID),
```

2023-09-11 19:57 UTC, ErikMurmi commented on webapi/Models/Reserva.cs
> +        public TimeSpan Hora_inicio { get; set; }
TimeSpan guarda un intervalo de tiempo no una fecha u hora especifica, es decir podria representar una duracion de reserva ex. 2 horas, pero no puede representar la 12:00 AM

2023-09-11 19:57 UTC, ErikMurmi commented on webapi/Models/Reserva.cs
> +        public Solicitud SolicitudID { get; set; }
Se pueden renombrar estas variables que refieren a un elemento de otra tabla? Porque tienen el nombre [Clase]ID pero hace referencia a todo el objeto, no solo el id. Por legibilidad.

2023-09-12 02:58 UTC, titorjs commented on webapi/Models/Reserva.cs
> +        public Solicitud SolicitudID { get; set; }
No se pueden renombrar porque hacen referencias a campos de una tabla en realidad, aunque revisaré si las relaciones se pueden cambiar.

2023-09-12 03:04 UTC, merged