feature/tj/controlador-usuario-identity
ErikMurmi/reservas-udla pull request #3
Opened 2023-09-24 01:05 UTC by titorjs

Migración completada bajo el nombre ModeloCompleto.
Se encuentra implementado Identity.

2023-09-24 02:15 UTC, ErikMurmi requested changes

2023-09-24 02:15 UTC, ErikMurmi commented on docs/tito.md
Añadir al ignore

2023-09-24 02:15 UTC, ErikMurmi commented on webapi/Program.cs
> +//builder.Services.AddTransient<ReservasCanchasUdlaContext>();
Si ya no se usa mejor eliminar el comentario

2023-09-24 02:35 UTC, titorjs commented on webapi/Program.cs
> +//builder.Services.AddTransient<ReservasCanchasUdlaContext>();
Si se usa, se me pasó descomentarlo, estaba probando algo.

2023-09-25 00:43 UTC, ErikMurmi commented on webapi/Program.cs
> +//builder.Services.AddTransient<ReservasCanchasUdlaContext>();
Dale 👍

2023-09-25 00:44 UTC, ErikMurmi approved these changes

2023-09-25 00:49 UTC, merged